#!/usr/bin/env bash
# Configure web-02 to be same as web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart

# Reference: https://www.cyberciti.biz/faq/nginx-send-custom-http-headers/
