#!/usr/bin/env bash
# Install and configure Highly Available Proxy

sudo apt-add-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo sed -i "\$ a\listen appname 0.0.0.0:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 261-web-01 34.229.124.172:80 check\n\tserver 261-web-02 34.234.82.4:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart

# Ref: https://www.cyberciti.biz/faq/nginx-send-custom-http-headers/
