#!/usr/bin/env bash
# Output "Holberton School" 10 times using while loop, with "Hi" on 9th loop
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if (( x == 9 ))
    then
	echo "Hi"
    fi
    (( x++ ))
done
