#!/usr/bin/env bash
# Output "Holberton School" 10 times, with 4th loop being "bad luck" and 8th loop being "good luck"
i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif (( i == 8 ))
    then
	echo "good luck"
    else
	echo "Holberton School"	
    fi
    (( i++ ))

done
