#!/usr/bin/env bash
# Output numbers from 1 - 20, with different strings for loop 4, 9, and 17

loop=1

while (( loop < 21 ))
do
    echo $loop

    case $loop in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac

    loop=$(( loop + 1 ))
done
