#!/usr/bin/env bash
# Run nginx process as user nginx on container server

sudo pkill apache2
sudo service apache2 stop
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sed -i "4i user nginx;" /etc/nginx/nginx.conf
chmod -R 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
